### ISSUE TITLE
fetch globals are not available

### ISSUE THREAD

**Issue by rebolyte** [bytecodealliance/ComponentizeJS#106] opened 2024-05-17 01:07 UTC
I see in the [tests](https://github.com/bytecodealliance/ComponentizeJS/blob/main/test/builtins/globals.js) that the global `Request`/`Response`/`Headers` objects are available, and I can create `Headers` successfully. But if I try to create `Request` or `Response` using the example, the module errors out with `wasm 'unreachable' instruction executed`:

```diff
diff --git a/example/hello.js b/example/hello.js
index 8671f41..fde2ac6 100644
--- a/example/hello.js
+++ b/example/hello.js
@@ -1,3 +1,11 @@
 export function hello (name) {
+  // const headers = new Headers();
+
+  const req = new Request('http://httpstat.us/200', {
+    method: 'GET',
+  });
+
+  // const res = new Response();
+
   return `Hello ${name}`;
 }
```

If I return `Reflect.ownKeys(globalThis).join(',')` from the function, I can see also see they're on the object. My end goal is to be able to run Hono inside the module, and it uses the native req/res objects. What am I missing?

**Comment by guybedford** [comment] 2024-05-17 01:42
Yes, this is a duplicate of https://github.com/bytecodealliance/ComponentizeJS/issues/96, which has root cause https://github.com/bytecodealliance/StarlingMonkey/issues/19.

It's not being actively worked on because the StarlingMonkey consumers all have a custom implementation, which is very unfortunate for adoption I know!

**Comment by tschneidereit** [comment] 2024-05-17 10:08
I am, slowly, working on the upstream bug, fwiw. It's a surprisingly big change to make fetch work properly, but it _is_ coming ☺️

**Comment by guybedford** [comment] 2024-08-28 18:23
Fixed in https://github.com/bytecodealliance/ComponentizeJS/pull/131.

**Closed by guybedford** 2024-08-28 18:23 UTC
